/* resourcemap.js generated by blorbtool.py */
StaticImageInfo = {
1: {
  "image": 1, 
  "url": "interpreter/pict-1.png", 
  "width": 960, 
  "height": 960
}
,
3: {
  "image": 3, 
  "url": "interpreter/pict-3.jpeg", 
  "width": 320, 
  "height": 209
}
,
4: {
  "image": 4, 
  "url": "interpreter/pict-4.png", 
  "width": 470, 
  "height": 618
}
,
5: {
  "image": 5, 
  "url": "interpreter/pict-5.png", 
  "width": 340, 
  "height": 356
}
};
